# Database connection for school PostgreSQL
spring.datasource.url=jdbc:postgresql://slon.felk.cvut.cz:5432/zubkovla
spring.datasource.username=zubkovla
spring.datasource.password=zubkovla_DBS212
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true